//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuiltEtmeCabasi
{


    public partial class BunyeIlacDuzenleme
    {

        /// <summary>
        /// pnl_guncelleme_basarili_bilgi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_guncelleme_basarili_bilgi;

        /// <summary>
        /// lbl_guncelleme_basarili_bilgi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_guncelleme_basarili_bilgi;

        /// <summary>
        /// pnl_guncelleme_basarisiz_bilgi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_guncelleme_basarisiz_bilgi;

        /// <summary>
        /// lbl_guncelleme_basarisiz_bilgi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_guncelleme_basarisiz_bilgi;

        /// <summary>
        /// txt_box_ilac_isim_duzenleme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_box_ilac_isim_duzenleme;

        /// <summary>
        /// txt_box_ilac_marka_duzenleme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_box_ilac_marka_duzenleme;

        /// <summary>
        /// txt_box_ilac_kategori_duzenleme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_box_ilac_kategori_duzenleme;

        /// <summary>
        /// txt_box_ilac_acikalam_duzenleme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_box_ilac_acikalam_duzenleme;

        /// <summary>
        /// link_btn_ilac_duzeneleme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton link_btn_ilac_duzeneleme;
    }
}
