//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuiltEtmeCabasi.WEB
{


    public partial class KategoriDuzenleme
    {

        /// <summary>
        /// pnl_duzenleme_basarili control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_duzenleme_basarili;

        /// <summary>
        /// lnl_duzenleme_basarili control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lnl_duzenleme_basarili;

        /// <summary>
        /// lnkbutton_duzenleme_basarili_kapatma control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_duzenleme_basarili_kapatma;

        /// <summary>
        /// pnl_duzenleme_basarisiz control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_duzenleme_basarisiz;

        /// <summary>
        /// lbl_duzenleme_basarisiz control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_duzenleme_basarisiz;

        /// <summary>
        /// lnkbutton_duzenleme_basarisiz_kapatma control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_duzenleme_basarisiz_kapatma;

        /// <summary>
        /// txt_kategoriDuzenlemeAdiMetinKutu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_kategoriDuzenlemeAdiMetinKutu;

        /// <summary>
        /// txt_kategoriDuzenlemeAciklamaMetinKutu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_kategoriDuzenlemeAciklamaMetinKutu;

        /// <summary>
        /// lnkbutton_duzenleme_button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_duzenleme_button;
    }
}
